
# First part: SEM 
# Get questionnaire data
# This dataset was generated by the late Henk Jabobs (2024).
# It contains data from 807 subjects x 2 conditions (Liking,Disliking) for 38 questions.
#load(file="Data/chapListenerDataKlara.RData")
#Data <- Data_2 %>% rename(Quality = KanoScore)
#save(file = "Data/chapListener_DataKlara2.RData", Data)
load(file="Data/chapListener_DataKlara2.RData") # loading Data

load(file = "Data/chapListener_Questions_dfQ_2.RData") # loading Questions_dfQ_2

#CodeQuestions_Eng <- read_excel("Data/CodeQuestions_Eng.xlsx")
#CodeQuestions <- CodeQuestions_Eng %>% select(code,indicator,question_eng) %>% rename(question = question_eng)
#save(file = "Data/chapListener_CodeQuestions.RData", CodeQuestions) # loading Questions_dfQ_2
load(file = "Data/chapListener_CodeQuestions.RData") # loading CodeQuestions) 
